lsst/felis

- felis/__init__.py
- felis/cli.py
- felis/utils.py
This adds some primitive operations on the graph that will aid in processing the descriptions from merged graphs.
Merging graphs is useful for specifying additional relationships across multiple files.
A merged graph will allow easy processing for validation of relationships across the documents; for example, we can query:
```
SELECT ?dpdd_rule_name WHERE {
<felis:Column> <prov:wasDerivedFrom> ?dpdd_rule_id .
?dpdd_rule_id <name> ?dpdd_rule_name .
}
```
> Add Graph Normalization and merging

- examples/merge/point-extra.yml
- examples/merge/point.yml
- felis/__init__.py
- felis/cli.py
- felis/tap.py
This adds a few different options for overriding the names of the TAP tables, either individually or with a postfix option (`--tap-tables-postfix`).
This also fixes a few issues around felis file merging as well provides an small example for merging.
> Add table name overrides to TAP schema names. Implement felis file merging.

- .pre-commit-config.yaml
- python/felis/cli.py
- python/felis/db/sqltypes.py
- python/felis/sql.py
- python/felis/tap.py
- python/felis/utils.py
- tests/test_sql.py
Few small changes to make it work with both 1.4 and 2.0, plus mypy updates for new sqlalchemy.
> DM-37744: Make felis compatible with sqlalchemy 2

- .github/workflows/build.yaml
- python/felis/cli.py
- python/felis/tap.py
- tests/test_cli.py
`create_mock_engine` does not actually return an Engine, but a MockConnection instance which has very different API. Updated TapLoadingVisitor to handle their differences correctly. Added unit test for `load-tap --dry-run`.
> DM-38304: Fix crash in `load-tap --dry-run` command

- python/felis/check.py
This replaces usage of the astropy check_ucd function with parse_ucd, catches any errors that occur, and prints them to the error log.
> DM-41218: Print detailed error messages when checking IVOA UCD syntax

- python/felis/cli.py
- python/felis/tap.py
- tests/test_tap.py
This is a fix for an issue where the `load-tap` command was failing at the command line due to how PyLD was configured. The default setting for object embedding when performing the JSON-LD "framing" was "@last," which embedded a referenced object once, after which its "@id" value was used, instead. The visitor class in Felis was processing the first constraint (foreign key) under the assumption that it would see a column object and not an "@id" reference. But for subsequent calls, it was only seeing the reference string value, which caused a crash.
When loading TAP, Felis is now configured to use the "@always" setting so that the column object data will be immediately accessible when processing constraints. The signature of the `cli._normalize()` method is updated so that the embed …
> DM-41890: Fix referencing problem with foreign key objects

- python/felis/cli.py
- python/felis/datamodel.py
- requirements.txt
- tests/test_datamodel.py
This PR adds a Pydantic v2 data model to felis describing the YAML schema format, as well as unit tests for the new module. A `validate` command was added to the CLI which will load any number of YAML files into Pydantic and print validation errors. This has been tested on all of the schemas in `sdm_schemas/yml`.
To run tests covering the new module:
```
cd tests && python -m unittest test_datamodel
```
To run validation on all of the SDM schemas using the CLI tool:
```
felis validate ../sdm_schemas/yml/*.yaml
```
These changes make no attempt to replace usage of the existing "simple" model that is used throughout Felis. All existing functionality should be unaffected.
For more details, please see the message on this PR's single commit. Updates to the Felis documentation will be …
> DM-41688: Add Pydantic data model to felis

- .github/workflows/build.yaml
- pyproject.toml
- setup.cfg
Configuration was updated so that felis will be pip installable using:
```    
pip install felis
```
The DM developer documentation was used for guidance:
https://developer.lsst.io/stack/building-with-pip.html
Existing configuration was moved from setup.cfg to pyproject.toml where relevant.
A new job was added to `build.yaml` which publishes the package to PyPI.
A valid token needs to be added as a project secret called `PYPI_UPLOADS` for the publication to work.
> DM-41289: Make Felis fully pip installable

- python/felis/tap.py
The TapLoadingVisitor was modified so that constraints are created in a second pass over the schema. This ensures that columns which may be referenced have been defined. The change was tested successfully using "load-tap" from the command line, with and without the "--dry-run" argument. The TAP data loaded into a MySQL database correctly when using the non-mock connection. The schema from[ this PR](https://github.com/lsst/sdm_schemas/pull/165) was used for testing.
> DM-42293: Modify TAP visitor so constraints do not depend on column order

- requirements.txt
The requirements in DM-41289 were accidentally overwritten while resolving a conflict. This fixes them to match the ones in the pyproject.toml config.
> DM-41289: Fix requirements to match those in pyproject.toml

- tests/test_datamodel.py
The error message will be "Extra inputs are not allowed."
> DM-41245: Add a test to confirm that using undefined YAML keys throws an error

- python/felis/datamodel.py
- tests/test_datamodel.py
The function for building a map of IDs to objects was rewritten using a visitor pattern, as the old version using recursion was prone to error and not working consistently. Duplicates are added to a set as the schema is visited. The `model_validator` function will throw an error if any duplicates are found, which will include a complete list of all the duplicate IDs. The new implementation of the ID builder and duplicate check was tested by running on several sdm_schemas which are known to contain duplicate IDs (imsim, hsc). These will be fixed in a different ticket branch on sdm_schemas.
> DM-42544: Add check for duplicate IDs when validating a schema

- python/felis/datamodel.py
- tests/test_datamodel.py
The `version` attribute can accept either string or `SchemaVersion` instance.
> DM-41029: Update Pydantic model for Schema class

- python/felis/cli.py
- tests/test_cli.py
Add a default of 0 so that a TypeError does not occur when the "--start-schema-at" option is unspecified.
> DM-42291: Provide a default argument for schema renumbering to modify-tap command

- python/felis/sql.py
When constraints are processed in order, the use of forward references to columns will cause an exception, as they have not been visited and created yet. Instead, the visitor is changed so that the tables are processed first and then these referenced columns will be available when creating constraints.
> DM-42787: Process constraints after tables are created in SQL visitor

- mypy.ini
- python/felis/cli.py
- python/felis/datamodel.py
- python/felis/types.py
- python/felis/validation.py
- tests/data/test.yml
- tests/test_cli.py
- tests/test_datamodel.py
- tests/test_simple.py
- tests/test_validation.py
RSP schema validation is implemented using a set of extension classes in a new validation module. The validation rules were based on those in the sdm_schemas repository under `tap-schema/validator`.
These new rules check that:
- All columns have a non-empty description
- All tables have a non-empty description, a TAP_SCHEMA table index, and at least one column flagged as TAP_SCHEMA principal
- The schema has a non-empty description and a set of unique (non-duplicated) TAP_SCHEMA table indices
Tests for the new module and its functionality were added under `tests/test_validation.py`.
A schema type can be selected from the command-line now using a syntax such as:
```
felis validate -s RSP ../sdm_schemas/yml/dp02_dc2.yaml
```
I tested the new validation on the above schema and found some …
> DM-42446: Add RSP schema validation

- python/felis/cli.py
- python/felis/datamodel.py
- python/felis/utils.py
- python/felis/validation.py
- tests/test_cli.py
- tests/test_datamodel.py
- tests/test_validation.py
This make changes suggested in review comments [here](https://github.com/lsst/felis/pull/31#pullrequestreview-1881543667
). The original PR was closed and merged before the second review occurred, so this is being done on a separate branch. All comments on the original PR should be resolved.
I made an additional change which was adding `from __future__ import annotations` to all of the Python files where it was missing.
I also added a few more simple tests in `test_datamodel.py` that check for various errors on the description field when the `require_description` flag is turned on.
> DM-42446: Implement minor fixes and improvements to Python syntax

- python/felis/tap.py
Import `declarative_base` from new module to resolve sqlalchemy deprecation warning.
Warning message was:
```
felis/tap.py:44: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
```
> Resolve sqlalchemy deprecation warning

- python/felis/datamodel.py
- python/felis/validation.py
Use Annotated along with TypeAlias to get rid of MyPy errors and improve how description strings are handled.
> Improve definition of description field

- python/felis/cli.py
Two command line options are added for setting the Felis log level and, optionally, an output file for log messages.
To set these using command line options:
```
felis --loglevel INFO --logfile ./log.txt validate yml/*.yaml
```
And they may also be set using environment variables:
```
export FELIS_LOGLEVEL=INFO
export FELIS_LOGFILE=./log.txt
```
These settings apply to the root logger which will also affect the child loggers. Different settings for each module logger are probably not needed right now.
> DM-43040: Add command line options for setting log level and file

- python/felis/cli.py
- python/felis/datamodel.py
- python/felis/db/sqltypes.py
- tests/test_cli.py
- tests/test_datamodel.py
- tests/test_datatypes.py
This adds a Pydantic validator that will identity variant type overrides, e.g., `mysql:datatype` values, that appear to be redundant. To determine whether the datatypes are the same, they are each compiled to a SQL snippet. If the resultant SQL is identical, then the type override is considered to be superfluous and an error is raised.
The validation needs to be turned on using the `-t/--check-redundant-datatypes` flag when running the `validate` command.
> DM-41247: Add tool that checks for redundant datatype definitions

- python/felis/cli.py
- python/felis/datamodel.py
- python/felis/db/sqltypes.py
- tests/test_cli.py
- tests/test_datamodel.py
- tests/test_datatypes.py
Revert #54 which itself reverted #50 
Fix the dependence on global state by using [Pydantic context](https://docs.pydantic.dev/latest/concepts/validators/#validation-context) instead.
Summary of changes:
- Use Pydantic `context` object instead of globals for validation flags and remove all class variables from `Schema` controlling validation behavior.
- Turn `validate_assignment` off for now as it can lead to undesirable validation behavior.
- Change the validation of descriptions to an "after" rather than "before" validator and use `ValidationInfo` instead of a global flag.
- Change the `DataType` enum in `datamodel` to `StrEnum` so it can be used interchangeably where a string value is required.
- Add `string_to_typeengine` utility for converting datatype strings to SQLAlchemy types.
- …
> DM-41247: Implement redundant data type checking with fix for global validation state

- python/felis/db/_variants.py
- python/felis/db/sqltypes.py
- python/felis/types.py
- tests/data/sales.yaml
The length should not be required when defining a text column, since it represents an unbounded string. The `is_sized` flag in Felis forces a column with that type to require a length, which we do not want for this datatype.
> DM-42257: Make the text type un-sized so length is not required

- python/felis/db/sqltypes.py
- tests/test_datatypes.py
Felis currently maps the boolean type to `BIT(1)` in MySQL, but it would be better to use its standard `BOOLEAN` datatype instead. This would make the usage of `mysql:datatype: BOOLEAN` in some of the columns a redundant override that should be removed, which is intended.
> DM-43751: Change default type mapping for boolean to BOOLEAN for MySQL

- python/felis/datamodel.py
Overrides that are not considered validation errors will print a `DEBUG` level message like this on one line instead of two now:
```
DEBUG:felis.datamodel:Type override of 'datatype: timestamp' with 'mysql_datatype: DATETIME' in column '#DiaObject.lastNonForcedSource' compiled to 'TIMESTAMP' and 'DATETIME'
```
Those that are redundant and considered validation errors will show like this, with the column's length in the error message (if applicable):
```
Value error, 'mysql_datatype: VARCHAR(64)' is a redundant override of 'datatype: string' in column '#DiaObject.nearbyLowzGal' with length 64
```
Text was changed so that "redundant override" can be used when grep'ing through the logs for errors.
> Improve the log statements and error messages in the redundant type checking validation

- python/felis/cli.py
- python/felis/datamodel.py
- python/felis/tap.py
- tests/test_tap.py
The tap module is updated to use the Pydantic data model, instead of the raw YAML. The "load-tap" command in the command line interface was also updated to use the Pydantic schema object. The PYLD transformations were removed from the cli function, as they seemed to be unnecessary. A few changes were made to the Pydantic data model to support setting of reasonable defaults. A "votable_datatype" annotation was added to Colum. The Column datatype was changed to return the enum instead of a string, as this setting seemed to confuse mypy. Tests were changed to conform to the new tap module and the minor changes to the data model. Testing showed that the schema was loaded correctly into a live PostgreSQL database.
> DM-42935: Refactor tap module to use the Pydantic data model

- python/felis/datamodel.py
- python/felis/metadata.py
The previous approach, which made numeric columns non-nullable while other types were nullable, was not logical considering that SQL columns in DDL are always nullable by default.
> DM-43753: Make columns nullable by default in the data model

- pyproject.toml
This should fix a Jenkins build error in `lsst_distrib`.
> DM-43597: Remove RUF100 from ruff config

- .github/workflows/lint.yaml
- .pre-commit-config.yaml
- pyproject.toml
- python/felis/datamodel.py
- python/felis/db/sqltypes.py
- python/felis/tap.py
- python/felis/validation.py
Update the ruff configuration for Python code linting and fix reported errors in the codebase.
Changes included:
- Updated all pre-commit repo versions using `pre-commit autoupdate`
- Updated `lint.yaml` workflow to run `ruff-action`
- Replaced ruff config in `pyproject.toml` with daf_butler's
- Added a few additional items to ruff's ignore list (D203, D213, D413)
- Sorted the ruff ignore list alphabetically so it was easier to manage
- Fixed all style errors reported by `ruff` based on the new configuration
Jenkins CI has passed on this branch:
https://rubin-ci.slac.stanford.edu/blue/organizations/jenkins/stack-os-matrix/detail/stack-os-matrix/1243/pipeline
> Update ruff config and fix style errors

- python/felis/datamodel.py
- python/felis/metadata.py
- tests/data/sales.yaml
- tests/data/test.yml
- tests/test_datamodel.py
This fixes the handling of the `value` field when creating SQLAlchemy metadata. String literals are quoted, except when the value is a SQL function such as `CURRENT_TIMESTAMP`. In this case, quotes are omitted.
A thorough validation function was also added to the data model for checking `value` if it was provided. This will make sure that the provided value is valid given the datatype of the column.
Finally, a new test method was added to check the validation function for all of the Felis datatypes, both when valid and invalid data is provided.
> DM-43998: Properly validate default values and fix their handling in SQL metadata

- python/felis/datamodel.py
- tests/test_datamodel.py
- tests/test_validation.py
Add a standalone validation function that checks if a sized type has a length and raises an error if not.
Add a requirement that the length field in the data model is greater than zero.
Add lengths to some string columns in the tests, as length is always required now for `Column` objects.
This and the related [sdm_schemas PR](https://github.com/lsst/sdm_schemas/pull/212) have been [checked in CI](https://rubin-ci.slac.stanford.edu/blue/organizations/jenkins/stack-os-matrix/detail/stack-os-matrix/1311/pipeline).
> DM-43371: Add validation of length for sized datatypes

- .github/workflows/docstyle.yaml
- python/felis/cli.py
- Remove full docstring from `cli()` function
- Override docstrings for commands with the `help` parameter
- Ignore `cli.py` in numpydoc validation, as this module need not conform to that formatting
> Fix command help in cli

- python/felis/datamodel.py
- python/felis/db/sqltypes.py
- python/felis/metadata.py
- tests/test_datamodel.py
- tests/test_metadata.py
Implement improvements to timestamps as described in [RFC-1027](https://rubinobs.atlassian.net/browse/RFC-1027):
- Set `timezone=False` when instantiating timestamp types
- Introduce a `precision` attribute on the `Column` data model
- Map the Felis timestamp type to `DATETIME` in MySQL
[RFC-1027]: https://rubinobs.atlassian.net/browse/RFC-1027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DM-44825: Improve support for timestamp handling

- python/felis/datamodel.py
- tests/test_datamodel.py
The `precision` field is used for specifying the precision of the seconds component on timestamp columns and is disallowed for all other datatypes.
This is an extra check on the data model added as part of [DM-44825](https://rubinobs.atlassian.net/browse/DM-44825), which improves timestamp support in Felis.
[DM-44825]: https://rubinobs.atlassian.net/browse/DM-44825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DM-44825: Check that precision is only allowed for timestamp columns

- python/felis/db/utils.py
- tests/test_cli.py
Sets paramstyle=pyformat in the create_mock_engine call in db/utils.py. This addresses the issue where changes to mysql:// as the engine_url breaks at the step of producing the insert statements, as mysql engine in sqlalchemy defaults to named params.
Extends the test_cli.test_load_tap_mock test to run on all known dialects
> Use the pyformat paramstyle for all mock_engines

- README.rst
- python/felis/db/dialects.py
- python/felis/db/sqltypes.py
Triggered by [RFC-1029](https://rubinobs.atlassian.net/browse/RFC-1029), remove support for Oracle datatypes and drop from supported database dialects.
This version of the user guide in `docs` is not modified, because it is being completely rewritten as part of [DM-43800](https://rubinobs.atlassian.net/browse/DM-43800), which removes mention of Oracle.
[RFC-1029]: https://rubinobs.atlassian.net/browse/RFC-1029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DM-43800]: https://rubinobs.atlassian.net/browse/DM-43800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DM-45191: Remove support for Oracle database dialect and data types

- python/felis/tap.py
Rewrite the logic for setting arraysize so that it is simpler and does not check if the Felis type is sized.
Instead set arraysize from the column or use it's length if arraysize is not set. For timestamp or text columns, set the arraysize to '*' if it was not set explicitly in the schema.
> Fix arraysize not being set for text columns

- python/felis/datamodel.py
- python/felis/tap.py
- tests/test_tap.py
- Set the `size` attribute based on the value of `votable_arraysize` from the column
- If arraysize is an int in the YAML data or a string that is parseable as an int, set size=arraysize
- If arraysize has the form "N*" where N is an int, set size=N
- For all other cases, size will default to `None` which will result in a null being inserted. This includes the case where arraysize is `*` or a blank string.
- Change the `votable_arraysize` field on the Pydantic model to accept a string or an integer
- The field was too restrictive based on the valid values from the IVOA VOTable standard.
- Fix bad type hint in `test_tap`
> DM-44878: Fill in the TAP_SCHEMA size attribute

- .github/workflows/build.yaml
- Makefile
- docs/dev/internals.rst
- docs/user-guide/databases.rst
- docs/user-guide/intro.rst
- python/felis/cli.py
- python/felis/datamodel.py
- python/felis/db/dialects.py
- python/felis/db/sqltypes.py
- python/felis/db/utils.py
- python/felis/db/variants.py
- python/felis/metadata.py
- python/felis/tests/postgresql.py
- tests/test_cli.py
- tests/test_postgresql.py
Change `--create-if-not-exists` option to `--initialize` and throw an error if the schema already exists in the database. To update an existing database, this option should be omitted. This flag will be ignored for SQLite, as tables can be created in a new database file automatically provided that the engine URL is valid.
Change `--drop-if-exists` option to `--drop`. This will drop and then recreate a schema if it exists. If the schema does not exist, then this is a no-op.
The `--drop` and `--initialize` options were made mutually exclusive and an error will be throw if they are used together. The `--drop` flag always activates initialization, as the database needs to be recreated if it was dropped or does not exist.
Add drop operation support for SQLite, which will remove all the …
> DM-45492: Change names of several create command options

- python/felis/cli.py
- python/felis/metadata.py
- tests/test_cli.py
- tests/test_metadata.py
- types.txt
Because so many files in SDM Schemas cannot be loaded into a database due to missing indices on foreign key columns, a flag is introduced for ignoring all constraints to avoid these errors, mainly to support testing of database creation for all schemas. Check and unique constraints are currently unused, so no other types of constraints besides foreign key constraints are defined in any of the YAML schema files. Long-term, we may consider adding indices on all FK target columns, but this may not be possible for all schemas.
Add test of this flag for the CLI and when creating metadata.
Also change the environment variable for the database connection URL to `FELIS_ENGINE_URL` from `ENGINE_URL` to avoid possible conflicts with other applications. (I thought this was already what it was. …
> DM-45485: Add flag for ignoring constraints in schema files

- docs/changes/DM-45623.feature.rst
- docs/conf.py
- docs/user-guide/databases.rst
- python/felis/datamodel.py
- tests/test_datamodel.py
Add a check at the schema level that constraints are uniquely named.
This is necessary because TAP_SCHEMA uses the `name` field of a foreign key constraint as the primary key of the `keys` table.
> DM-45623: Add check that constraint names are unique within a schema

- docs/user-guide/databases.rst
- python/felis/datamodel.py
Change the default MySQL table engine to MyISAM in the data model, for two main reasons:
- This is the table engine used by Qserv, so we want to match it as closely as possible.
- Some of the tables are exceeding the maximum number of columns allowed by the InnoDB engine.
> DM-45725: Change default table engine to MyISAM

- docs/CHANGES.rst
- pyproject.toml
This just updates the title format to put the date in parentheses in `CHANGES.rst` and in the `title_format` in `pyproject.toml`.
Also take out `:html_theme.sidebar_secondary.remove:` from `CHANGES.rst`. The sidebar will look fine when there are multiple releases.
> Update towncrier title format

- docs/changes/DM-46002.bugfix.rst
- python/felis/datamodel.py
- python/felis/metadata.py
- python/felis/tap.py
- tests/test_datamodel.py
This fixes an issue where the Pydantic error locations for constraint objects were reported incorrectly, due to how the model objects were constructed.
Instead of using a custom `create_constraints()` function, a Pydantic [discriminated union](https://docs.pydantic.dev/latest/concepts/unions/#discriminated-unions-with-str-discriminators) was used to automatically construct the objects based on the `type` field. This seems to fix the issue where error locations were reported incorrectly.
Sample new error location is: `tables.0.constraints.0.Unique.@id`.
This is not exactly the same scheme that shows for some other types of objects, but it is at least clear now that the error has occurred in a specific constraint denoted by the index.
As a result of the above changes, usage of the `type` …
> DM-46002: Locations for validation errors on constraints reported incorrectly

- python/felis/tap.py
Fix obvious bug where wrong arraysize variable was being used in setting size.
Do not set arraysize automatically for fields with length of 1.
> Fix bugs in how size and arraysize were being handled

- .github/workflows/build.yaml
- docs/changes/DM-47900.misc
- pyproject.toml
Add Python 3.13 to the build matrix and supported versions.
This was separated from #109 by request of @gpdf.
> DM-47900: Add Python 3.13 support

- python/felis/metadata.py
- python/felis/tap_schema.py
- tests/test_metadata.py
- tests/test_tap_schema.py
> DM-46957: Add an optional table name postfix to the metadata builder

- python/felis/datamodel.py
- tests/data/test_id_generation.yaml
The id generation was missing for column groups.
> Generate ids for column groups

- docs/changes/DM-47602.misc.rst
- docs/dev/internals.rst
- python/felis/tests/run_cli.py
- tests/test_cli.py
This PR introduces a small utility module for running CLI commands in tests to avoid duplication.
All of the tests in `tests/test_cli.py` were refactoring to use the new module.
> DM-47602: Reorganize and refactor Felis CLI tests

- docs/changes/DM-45133.feature
- python/felis/datamodel.py
- tests/test_datamodel.py
- Add a validator to automatically set the `votable_xtype` to "timestamp" on Felis timestamp columns.
> DM-45133: Set xtype on timestamp columns

- docs/changes/DM-46240.api.rst
- python/felis/cli.py
- tests/data/test_diff1.yaml
- tests/data/test_diff2.yaml
- tests/test_cli.py
> DM-46240: Turn on generation of IDs by default

- docs/user-guide/model.rst
> Fix typo in foreign key constraint documentation
